name: Codeowners Plus Rerun

on:
  workflow_dispatch:

permissions: {}

jobs:
  rerun-codeowners-plus:
    name: Rerun Codeowners Plus
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
      checks: read
    steps:
      - name: Rerun the Codeowners Plus check
        uses: shqear93/rerun-checks@cafa5c1c11c880f9b23e6a73ad8628483fdae798
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-names: Run Codeowners Plus
